server:
  port: 1234
  tomcat:
    uri-encoding: UTF-8
spring:
  # 连接数据库配置
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/xyg_dome?useUnicode=true&characterEncoding=utf-8&&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    # 关闭thymeleaf缓存
    cache: false
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
mybatis:
  type-aliases-package: com.xyg.entity
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
